export interface Citation {
  /** Stable key for <Cite id="..." /> */
  key: string
  /** Display number [1], [2], … */
  num: number
  title: string
  publisher?: string
  url?: string
  /** Short label for source lines and tooltips */
  short: string
}

const list: Citation[] = [
  {
    key: 'usgs-mcs',
    num: 1,
    title: 'Mineral Commodity Summaries — Silicon',
    publisher: 'U.S. Geological Survey (USGS)',
    url: 'https://pubs.usgs.gov/periodicals/mcs2023/mcs2023-silicon.pdf',
    short: 'USGS Mineral Commodity Summaries',
  },
  {
    key: 'sciencedirect-hpq',
    num: 2,
    title: 'High-purity quartz',
    publisher: 'ScienceDirect',
    url: 'https://www.sciencedirect.com/science/article/pii/S0009254121004502',
    short: 'ScienceDirect (HPQ)',
  },
  {
    key: 'bernreuter',
    num: 3,
    title: 'Polysilicon uses and market reports',
    publisher: 'Bernreuter Research / Wacker',
    url: 'https://www.bernreuter.com/polysilicon/uses/',
    short: 'Bernreuter Research',
  },
  {
    key: 'asml-gaa',
    num: 4,
    title: 'What is a gate-all-around transistor?',
    publisher: 'ASML',
    url: 'https://www.asml.com/en/news/stories/2022/what-is-a-gate-all-around-transistor',
    short: 'ASML',
  },
  {
    key: 'intel-strain',
    num: 5,
    title: 'Strained transistors and process technology',
    publisher: 'Intel (arquivo)',
    url: 'https://web.archive.org/web/20101125112707/https://www.intel.com/pressroom/kits/advancedtech/doodle/ref_strain/strain.htm',
    short: 'Intel (strained silicon)',
  },
  {
    key: 'zulehner-2000',
    num: 6,
    title: 'Czochralski growth of silicon',
    publisher: 'Materials Science and Engineering: B, 73(1–3), 7–15',
    short: 'Zulehner (2000)',
  },
  {
    key: 'moller-2012',
    num: 7,
    title: 'Silicon materials for solar cells',
    publisher: 'Progress in Materials Science, 57(7), 1285–1338',
    short: 'Möller (2012)',
  },
  {
    key: 'runnels-1994',
    num: 8,
    title: 'Tribology analysis of chemical-mechanical polishing',
    publisher: 'J. Electrochemical Society, 141(6), 1698',
    short: 'Runnels & Eyman (1994)',
  },
  {
    key: 'kern-1990',
    num: 9,
    title: 'The evolution of silicon wafer cleaning technology',
    publisher: 'J. Electrochemical Society, 137(6), 1887',
    short: 'Kern (1990)',
  },
  {
    key: 'pv-education',
    num: 10,
    title: 'Manufacturing Si cells — silicon wafers and substrates',
    publisher: 'PV Education (PVCDROM)',
    url: 'https://www.pveducation.org/pvcdrom/welcome-to-pvcdrom/manufacturing-si-cells',
    short: 'PV Education',
  },
  {
    key: 'csiro',
    num: 11,
    title: 'Silicon and ferrosilicon production',
    publisher: 'CSIRO',
    url: 'https://www.csiro.au/',
    short: 'CSIRO',
  },
  {
    key: 'saimm',
    num: 12,
    title: 'Silicon processing: from quartz to crystalline silicon solar cells',
    publisher: 'Xakalashe & Tangstad — Southern African Pyrometallurgy 2011, SAIMM',
    url: 'https://pyrometallurgy.co.za/Pyro2011/Papers/083-Xakalashe.pdf',
    short: 'Xakalashe & Tangstad (2011)',
  },
  {
    key: 'elkem',
    num: 13,
    title: 'Silicon production and materials',
    publisher: 'Elkem',
    url: 'https://www.elkem.com/',
    short: 'Elkem',
  },
  {
    key: 'ratedpower',
    num: 14,
    title: 'What is polysilicon and how is it made?',
    publisher: 'RatedPower',
    url: 'https://ratedpower.com/glossary/polysilicon/',
    short: 'RatedPower',
  },
  {
    key: 'energy-central',
    num: 15,
    title: 'Polysilicon and semiconductor grade silicon',
    publisher: 'Energy Central',
    url: 'https://energycentral.com/',
    short: 'Energy Central',
  },
  {
    key: 'hkmg-paper',
    num: 16,
    title: 'High Performance High-K + Metal Gate Strain Enhanced Transistors on (110) S',
    publisher: 'Semantic Scholar, 2008',
    url: 'https://pdfs.semanticscholar.org/cd90/94aa1fd40650ba21d32d6b976f2f4b66a2d0.pdf',
    short: 'HKMG (Semantic Scholar)',
  },
  {
    key: 'intel-4004',
    num: 17,
    title: "Intel's First Microprocessor — the Intel 4004",
    publisher: 'Intel Museum (arquivo)',
    url: 'https://web.archive.org/web/20091226202754/http:/www.intel.com/museum/archives/4004.htm',
    short: 'Intel 4004',
  },
  {
    key: 'intel-chmos3',
    num: 18,
    title: 'A double layer metal CHMOS III technology',
    publisher: 'IEDM 1984 (Intel)',
    url: 'https://doi.org/10.1109/iedm.1984.190640',
    short: 'Intel CHMOS III',
  },
  {
    key: 'intel-p856',
    num: 19,
    title: 'Intel Technology Journal — the 0.25 µm P856 process',
    publisher: 'Intel, 1998',
    url: 'https://www.intel.com/content/dam/www/public/us/en/documents/research/1998-vol02-iss-3-intel-technology-journal.pdf',
    short: 'Intel P856',
  },
  {
    key: 'voldman-esd',
    num: 20,
    title: 'Evolution, Revolution, and Technology Scaling — The Impact on ESD and EOS Reliability',
    publisher: 'Frontiers in Materials, 2018',
    url: 'https://www.frontiersin.org/journals/materials/articles/10.3389/fmats.2018.00033/full',
    short: 'Voldman (2018)',
  },
  {
    key: 'ibm-cell',
    num: 21,
    title: 'Introduction to the Cell multiprocessor',
    publisher: 'IBM Journal of R&D, 2005',
    url: 'https://www.mirrorservice.org/sites/www.bitsavers.org/pdf/ibm/IBM_Journal_of_Research_and_Development/494/kahle.pdf',
    short: 'IBM JRD (Cell, SOI)',
  },
  {
    key: 'intel-90nm',
    num: 22,
    title: 'Intel Introduces Pentium 4 Processors on High-Volume 90-nanometer Manufacturing Technology',
    publisher: 'Intel (comunicado, 2004)',
    url: 'https://www.intel.com/pressroom/archive/releases/2004/20040202comp.htm',
    short: 'Intel 90 nm',
  },
  {
    key: 'intel-45nm',
    num: 23,
    title: "Intel's Fundamental Advance in Transistor Design Extends Moore's Law",
    publisher: 'Intel (comunicado, 2007)',
    url: 'https://www.intel.com/pressroom/archive/releases/20071111comp.htm',
    short: 'Intel 45 nm Hi-k',
  },
  {
    key: 'intel-trigate',
    num: 24,
    title: 'Intel Reinvents Transistors Using New 3-D Structure',
    publisher: 'Intel (comunicado, 2011)',
    url: 'https://www.intc.com/news-events/press-releases/detail/655/intel-reinvents-transistors-using-new-3-d-structure',
    short: 'Intel Tri-Gate',
  },
  {
    key: 'techinsights-22fdx',
    num: 25,
    title: 'Synaptics AS-370 SmartAudio Processor — GlobalFoundries 22 nm FDSOI (22FDX) process',
    publisher: 'TechInsights',
    url: 'https://www.techinsights.com/products/ace-2001-802',
    short: 'TechInsights (22FDX)',
  },
  {
    key: 'techinsights-gaa',
    num: 26,
    title: 'MicroBT KF1978E Whatsminer M56S++ Samsung SF3E Process Flow Analysis',
    publisher: 'TechInsights',
    url: 'https://www.techinsights.com/blog/microbt-kf1978e-whatsminer-m56s-samsung-sf3e-process-flow-analysis',
    short: 'TechInsights (GAA)',
  },
  {
    key: 'tsmc-n2',
    num: 27,
    title: '2nm Technology (N2) — first-generation nanosheet transistor',
    publisher: 'TSMC',
    url: 'https://www.tsmc.com/english/dedicatedFoundry/technology/logic/l_2nm',
    short: 'TSMC N2',
  },
  {
    key: 'imec-forksheet',
    num: 28,
    title: 'Outer wall forksheet: bridging nanosheet and CFET device architectures',
    publisher: 'imec',
    url: 'https://www.imec-int.com/en/articles/outer-wall-forksheet-bridge-nanosheet-and-cfet-device-architectures-logic-technology',
    short: 'imec forksheet',
  },
  {
    key: 'intel-18a',
    num: 29,
    title: 'CES 2026: Intel Core Ultra Series 3 Debuts as First Built on Intel 18A',
    publisher: 'Intel (comunicado, 2026)',
    url: 'https://www.intc.com/news-events/press-releases/detail/1757/ces-2026-intel-core-ultra-series-3-debuts-as-first-built',
    short: 'Intel 18A',
  },
  {
    key: 'verisilicon-fdsoi',
    num: 30,
    title: 'VeriSilicon launches FD-SOI wireless IP platform for IoT and consumer electronics',
    publisher: 'TechToday',
    url: 'https://techtoday.co/verisilicon-launches-fd-soi-wireless-ip-platform-for-iot-consumer-electronics/',
    short: 'VeriSilicon (FD-SOI)',
  },
  {
    key: 'pv-mfg-polysilicon',
    num: 31,
    title: 'Polysilicon Production',
    publisher: 'PV-Manufacturing.org',
    url: 'https://pv-manufacturing.org/silicon-production/polysilicon-production/',
    short: 'PV-Manufacturing.org',
  },
  {
    key: 'shmj-sti',
    num: 32,
    title: 'Adoption of shallow trench isolation (STI)',
    publisher: 'Semiconductor History Museum of Japan',
    url: 'https://www.shmj.or.jp/english/pdf/process/exhibi408E.pdf',
    short: 'SHMJ (STI)',
  },
  {
    key: 'intel-80386',
    num: 33,
    title: 'Introduction to the 80386',
    publisher: 'Intel, abril de 1986',
    url: 'https://bitsavers.org/components/intel/80386/231746-001_Introduction_to_the_80386_Apr86.pdf',
    short: 'Intel 80386 (1986)',
  },
  {
    key: 'asianometry-euv',
    num: 34,
    title: '“The Decision of the Century”: Choosing EUV Lithography',
    publisher: 'Asianometry (vídeo)',
    url: 'https://www.youtube.com/watch?v=RmgkV83OhHA',
    short: 'Asianometry (EUV)',
  },
  {
    key: 'sematech-ngl',
    num: 35,
    title: 'NGL process and the role of International SEMATECH',
    publisher: 'SPIE (International SEMATECH)',
    url: 'https://doi.org/10.1117/12.472289',
    short: 'International SEMATECH (NGL)',
  },
  {
    key: 'cset-euv',
    num: 36,
    title: 'Tracing the Emergence of Extreme Ultraviolet Lithography',
    publisher: 'CSET, Georgetown University',
    url: 'https://cset.georgetown.edu/wp-content/uploads/CSET-Tracing-the-Emergence-of-Extreme-Ultraviolet-Lithography.pdf',
    short: 'CSET (EUV)',
  },
  {
    key: 'intel-euvllc',
    num: 37,
    title: 'Government-Industry Partnership To Develop Advanced Lithography Technology',
    publisher: 'Intel (comunicado, setembro de 1997)',
    url: 'https://www.intel.com/pressroom/archive/releases/1997/CN091197.HTM',
    short: 'EUV LLC (1997)',
  },
  {
    key: 'kato-litho',
    num: 38,
    title: 'Chronology of Lithography Milestones',
    publisher: 'Kato, lithoguru.com',
    url: 'https://www.lithoguru.com/scientist/litho_history/Kato_Litho_History.pdf',
    short: 'Kato (cronologia)',
  },
  {
    key: 'chiphistory-litho',
    num: 39,
    title: 'Lithography tool and competitive transition history',
    publisher: 'chiphistory.org',
    url: 'https://www.chiphistory.org/750-lithography-tool-and-competitive-transition-history',
    short: 'chiphistory.org',
  },
  {
    key: 'construction-physics-euv',
    num: 40,
    title: 'How ASML Got EUV',
    publisher: 'Construction Physics',
    url: 'https://www.construction-physics.com/p/how-asml-got-euv',
    short: 'Construction Physics (EUV)',
  },
  {
    key: 'asml-immersion',
    num: 41,
    title: 'How immersion lithography saved Moore’s Law',
    publisher: 'ASML',
    url: 'https://www.asml.com/en/company/stories/2023/how-immersion-lithography-saved-moores-law',
    short: 'ASML (imersão)',
  },
  {
    key: 'lin-immersion',
    num: 42,
    title: 'Hot-lot equivalent of technology development — immersion lithography',
    publisher: 'J. Micro/Nanolithography, MEMS and MOEMS (Burn J. Lin, TSMC)',
    url: 'https://doi.org/10.1117/1.1695567',
    short: 'Lin (imersão)',
  },
  {
    key: 'spectrum-epl',
    num: 43,
    title: 'Loser: A promising lithography gets stuck',
    publisher: 'IEEE Spectrum',
    url: 'https://spectrum.ieee.org/loser-a-promising-lithography-gets-stuck',
    short: 'IEEE Spectrum (EPL)',
  },
  {
    key: 'eet-euvlith',
    num: 44,
    title: 'EUV gains as venture ends e-beam litho work',
    publisher: 'EE Times',
    url: 'https://www.eetimes.com/euv-gains-as-venture-ends-e-beam-litho-work/',
    short: 'EE Times (EPL)',
  },
  {
    key: 'ldd-08um',
    num: 45,
    title: 'An 0.8 µm CMOS technology for high performance logic applications',
    publisher: 'IEDM 1987',
    url: 'https://doi.org/10.1109/iedm.1987.191432',
    short: 'Chapman et al. (1987)',
  },
  {
    key: 'semi-m1',
    num: 46,
    title: 'SEMI M1 — Specification for Polished Single Crystal Silicon Wafers',
    publisher: 'SEMI International Standards',
    url: 'https://store-us.semi.org/products/m00100-semi-m1-specification-for-polished-single-crystal-silicon-wafers',
    short: 'SEMI M1',
  },
  {
    key: 'asianometry-wafer',
    num: 47,
    title: 'The Amazing, Humble Silicon Wafer',
    publisher: 'Asianometry (vídeo)',
    url: 'https://www.youtube.com/watch?v=sIRfWyyOFPg',
    short: 'Asianometry (wafer)',
  },
  {
    key: 'sibelco-hpq',
    num: 48,
    title: 'High Purity Quartz — IOTA®',
    publisher: 'Sibelco',
    url: 'https://www.sibelco.com/en/materials/high-purity-quartz',
    short: 'Sibelco (HPQ)',
  },
  {
    key: 'quartzcorp-hpq',
    num: 49,
    title: 'High Purity Quartz — history and processing',
    publisher: 'The Quartz Corp (Imerys / Norsk Mineral)',
    url: 'https://www.thequartzcorp.com/high-purity-quartz',
    short: 'The Quartz Corp',
  },
  {
    key: 'iucr-czochralski',
    num: 50,
    title: 'Who was Jan Czochralski? Out of the shadows',
    publisher: 'IUCr Newsletter, 28(3)',
    url: 'https://www.iucr.org/news/newsletter/volume-28/number-3/who-was-jan-czochralski',
    short: 'IUCr (Czochralski)',
  },
  {
    key: 'chm-grown-junction',
    num: 51,
    title: '1951: First Grown-Junction Transistors Fabricated',
    publisher: 'Computer History Museum — The Silicon Engine',
    url: 'https://www.computerhistory.org/siliconengine/first-grown-junction-transistors-fabricated/',
    short: 'Computer History Museum',
  },
  {
    key: 'ge-vs-si',
    num: 52,
    title: 'Germanium: From its discovery to SiGe devices',
    publisher: 'Materials Science in Semiconductor Processing, 9(4–5)',
    url: 'https://www.sciencedirect.com/science/article/abs/pii/S1369800106001326',
    short: 'Claeys & Simoen (germânio)',
  },
  {
    key: 'intel-450mm',
    num: 53,
    title: 'Intel, Samsung Electronics, TSMC Reach Agreement for 450mm Wafer Manufacturing Transition',
    publisher: 'Intel (comunicado, maio de 2008)',
    url: 'https://www.intc.com/news-events/press-releases/detail/942/intel-samsung-electronics-tsmc-reach-agreement-for-450mm',
    short: 'Intel 450 mm (2008)',
  },
  {
    key: 'eng-450mm',
    num: 54,
    title: '450 mm Silicon Wafers Are Imperative for Moore’s Law but maybe Postponed',
    publisher: 'Engineering (Chinese Academy of Engineering)',
    url: 'https://www.engineering.org.cn/engi/EN/10.15302/J-ENG-2015060',
    short: 'Engineering (450 mm)',
  },
  {
    key: 'nikkei-wafer-share',
    num: 55,
    title: '主要商品・サービスシェア調査 — participação de mercado em wafers de silício',
    publisher: 'Nikkei (pesquisa 2024, publicada em setembro de 2025)',
    url: 'https://www.nikkei.com/article/DGXZQOUC0608C0W5A800C2000000/',
    short: 'Nikkei (market share)',
  },
  {
    key: 'pv-tech-dws',
    num: 56,
    title: 'Diamond wire sawing: state of the art and perspectives',
    publisher: 'PV-Tech',
    url: 'https://www.pv-tech.org/wp-content/uploads/legacy-publication-pdfs/fb14522c21-diamond-wire-sawing-state-of-the-art-and-perspectives.pdf',
    short: 'PV-Tech (fio diamantado)',
  },
  {
    key: 'nae-teal',
    num: 57,
    title: 'Dr. Gordon K. Teal — memorial tribute',
    publisher: 'National Academy of Engineering',
    url: 'https://www.nae.edu/28465/Dr-Gordon-K-Teal',
    short: 'NAE (Teal)',
  },
  {
    key: 'teal-buehler-1952',
    num: 58,
    title: 'Growth of silicon single crystals and of single-crystal silicon p-n junctions',
    publisher: 'Teal & Buehler — Physical Review, 87(1), 190',
    short: 'Teal & Buehler (1952)',
  },
  {
    key: 'wafer-market',
    num: 59,
    title: 'Silicon wafer market — size, share and industry analysis',
    publisher: 'IMARC Group',
    url: 'https://www.imarcgroup.com/silicon-wafer-market',
    short: 'IMARC (mercado de wafers)',
  },
  {
    key: 'elkem-solar-route',
    num: 60,
    title: "Solar-grade silicon — is 'Siemens' the only answer?",
    publisher:
      'Odden, Søiland, Enebakk, Braathen, Sandberg & Friestad (Elkem Solar) — Photovoltaics International, ed. 16, May 2012',
    url: 'https://www.pv-tech.org/wp-content/uploads/legacy-publication-pdfs/014325526f-solargrade-silicon-is-siemens-the-only-answer.pdf',
    short: 'Elkem Solar — rota metalúrgica',
  },
  {
    key: 'elkem-lca',
    num: 61,
    title: 'Environmental footprint of Elkem Solar Silicon',
    publisher: 'de Wild-Scholten & Gløckner (2012)',
    url: 'https://smartgreenscans.nl/publications/deWildScholten-and-Glockner-2012-Environmental-footprint-of-Elkem-Solar-Silicon.pdf',
    short: 'LCA do silício Elkem Solar',
  },
  {
    key: 'rec-solar-epd',
    num: 62,
    title: 'Solar grade silicon (SoG-Si) — Environmental Product Declaration, Fiskå',
    publisher: 'REC Solar Norway AS / EPD-Norge (2020)',
    url: 'https://www.recgroup.com/sites/default/files/documents/nepd-2681-1371_rec-solar-solar-grade-silicon-sog-si-.pdf',
    short: 'EPD do silício grau solar (REC)',
  },
  {
    key: 'rec-closure-2023',
    num: 63,
    title: 'REC closes Norwegian polysilicon production facilities',
    publisher: 'pv magazine (2023)',
    url: 'https://www.pv-magazine.com/2023/11/23/rec-closes-norwegian-polysilicon-production-facilities/',
    short: 'pv magazine — fechamento da REC (2023)',
  },
  {
    key: 'elkem-buys-rec',
    num: 64,
    title: "India's Reliance Industries offloads REC Solar Norway",
    publisher: 'TaiyangNews (2024)',
    url: 'https://taiyangnews.info/business/indias-reliance-industries-offloads-rec-solar-norway',
    short: 'TaiyangNews — Elkem compra a REC Norway',
  },
  {
    key: 'trendforce-2025',
    num: 65,
    title: 'Solar module, cell, wafer prices to rise in Q2 2025, says TrendForce',
    publisher: 'pv magazine / TrendForce (2025)',
    url: 'https://www.pv-magazine.com/2025/03/27/solar-module-cell-wafer-prices-to-rise-in-q2-2025-says-trendforce/',
    short: 'pv magazine — preços em 2025',
  },
  {
    key: 'snl-rec',
    num: 66,
    title: 'REC Solar Norway',
    publisher: 'Store norske leksikon',
    url: 'https://snl.no/REC_Solar_Norway',
    short: 'Store norske leksikon (REC)',
  },
  {
    key: 'pv-mfg-cz',
    num: 67,
    title: 'Cz monocrystalline silicon production',
    publisher: 'PV-Manufacturing.org',
    url: 'https://pv-manufacturing.org/silicon-production/cz-monocrystalline-silicon-production/',
    short: 'PV-Manufacturing.org (Cz)',
  },
  {
    key: 'itrpv-2024',
    num: 68,
    title: 'International Technology Roadmap for Photovoltaics (ITRPV) — 15th edition',
    publisher: 'VDMA',
    url: 'https://www.vdma.eu/documents/34570/16191053/2024-06-04+PR+VDMA+PV+ITRPV+2024+EN.pdf',
    short: 'ITRPV (15.ª edição)',
  },
  {
    key: 'lid-hallam',
    num: 69,
    title:
      'Eliminating light-induced degradation in commercial p-type Czochralski silicon solar cells',
    publisher: 'Hallam & Herguth et al. — Applied Sciences, 8(1), 10 (2018)',
    url: 'https://www.mdpi.com/2076-3417/8/1/10',
    short: 'Hallam & Herguth (2018)',
  },
  {
    key: 'ga-transition',
    num: 70,
    title: 'Historical market projections and the future of silicon solar cells',
    publisher: 'Vicari Stefani et al. (CSIRO/UNSW/Oxford) — Joule (2023)',
    url: 'https://doi.org/10.1016/j.joule.2023.11.006',
    short: 'Vicari Stefani et al. (2023)',
  },
  {
    key: 'letid-ga',
    num: 71,
    title:
      'LeTID sensitivity of gallium- & boron-doped Cz-Si PERC solar cells with an average conversion efficiency of 23.6%',
    publisher: 'AIP Conference Proceedings (2022)',
    url: 'https://doi.org/10.1063/5.0089271',
    short: 'LeTID em células dopadas com gálio (2022)',
  },
  {
    key: 'semi-mf928',
    num: 72,
    title: 'Test method for edge contour of circular semiconductor wafers and rigid disk substrates',
    publisher: 'SEMI MF928',
    url: 'https://store-us.semi.org/products/mf092800-semi-mf928-test-method-for-edge-contour-of-circular-semiconductor-wafers-and-rigid-disk-substrates',
    short: 'SEMI MF928',
  },
  {
    key: 'prostek-edge',
    num: 73,
    title: 'Semiconductor wafer edge analysis',
    publisher: 'ProStEK — technical note (metrology)',
    url: 'http://www.prostek.com/ch_data/Semiconductor%20Wafer%20Edge%20Analysis.pdf',
    short: 'ProStEK (wafer edge)',
  },
  {
    key: 'pei-2005',
    num: 74,
    title: 'A grinding-based manufacturing method for silicon wafers: an experimental investigation',
    publisher: 'Z. J. Pei et al. — Int. J. Machine Tools and Manufacture, 45(10), 1140–1151 (2005)',
    url: 'https://doi.org/10.1016/j.ijmachtools.2004.12.006',
    short: 'Pei et al. (2005)',
  },
  {
    key: 'dyer-1989',
    num: 75,
    title: 'A comparison of silicon wafer etching by KOH and acid solutions',
    publisher: 'L. D. Dyer et al. — J. Electrochemical Society, 136(10), 3016 (1989)',
    url: 'https://doi.org/10.1149/1.2096394',
    short: 'Dyer et al. (1989)',
  },
  {
    key: 'us-6346485',
    num: 76,
    title: 'Semiconductor wafer processing method and semiconductor wafers produced by the same',
    publisher: 'US Patent 6,346,485',
    url: 'https://patents.google.com/patent/US6346485B1/en',
    short: 'US 6,346,485',
  },
  {
    key: 'tokuda-1989',
    num: 77,
    title: 'Thermal donor annihilation and defect production in n-type silicon by rapid thermal annealing',
    publisher: 'Y. Tokuda et al. — Journal of Applied Physics, 66(8), 3651–3655 (1989)',
    url: 'https://doi.org/10.1063/1.344076',
    short: 'Tokuda et al. (1989)',
  },
  {
    key: 'stein-1986',
    num: 78,
    title: 'Rapid thermal annealing and regrowth of thermal donors in silicon',
    publisher: 'H. J. Stein, S. K. Hahn & S. C. Shatas — Journal of Applied Physics, 59(10), 3495–3502 (1986)',
    url: 'https://doi.org/10.1063/1.336820',
    short: 'Stein et al. (1986)',
  },
  {
    key: 'bernreuter-production',
    num: 79,
    title:
      'Polysilicon production processes: Siemens process, fluidized bed reactor, upgraded silicon metal',
    publisher: 'Bernreuter Research (Johannes Bernreuter)',
    url: 'https://www.bernreuter.com/polysilicon/production-processes/',
    short: 'Bernreuter Research (processes)',
  },
  {
    key: 'bernreuter-market',
    num: 80,
    title: 'Polysilicon market analysis: size, shares, trends and China',
    publisher: 'Bernreuter Research (Johannes Bernreuter)',
    url: 'https://www.bernreuter.com/polysilicon/market-analysis/',
    short: 'Bernreuter Research (market)',
  },
  {
    key: 'bernreuter-pork-cycle',
    num: 81,
    title: 'Why the pork cycle has returned to the polysilicon market',
    publisher: 'Johannes Bernreuter Research, 16 January 2024',
    url: 'https://www.bernreuter.com/newsroom/polysilicon-news/article/why-the-pork-cycle-has-returned-to-the-polysilicon-market/',
    short: 'Bernreuter (pork cycle)',
  },
  {
    key: 'wikipedia-tcs',
    num: 82,
    title: 'Trichlorosilane',
    publisher: 'Wikipedia (CC BY-SA 4.0)',
    url: 'https://en.wikipedia.org/wiki/Trichlorosilane',
    short: 'Wikipedia (trichlorosilane)',
  },
  {
    key: 'jarkin-2021',
    num: 83,
    title:
      'Methods of trichlorosilane synthesis for polycrystalline silicon production. Part 1: Direct synthesis; Part 2: Hydrochlorination and redistribution',
    publisher:
      'V. N. Jarkin, O. A. Kisarin, T. V. Kritskaya — Modern Electronic Materials 7(1): 1–10 and 7(2): 33–43 (2021), open access, CC BY 4.0',
    url: 'https://doi.org/10.3897/j.moem.7.1.64953',
    short: 'Jarkin et al. (TCS synthesis)',
  },
  {
    key: 'icsc-tcs',
    num: 84,
    title: 'ICSC 0591 — Trichlorosilane',
    publisher: 'International Chemical Safety Cards (WHO / ILO), inchem.org',
    url: 'https://www.inchem.org/documents/icsc/icsc/eics0591.htm',
    short: 'ICSC 0591 (trichlorosilane)',
  },
  {
    key: 'ieee-node',
    num: 85,
    title: 'A Better Way to Measure Progress in Semiconductors',
    publisher:
      'Samuel K. Moore — IEEE Spectrum (print edition, August 2020, as "The Node is Nonsense")',
    url: 'https://spectrum.ieee.org/a-better-way-to-measure-progress-in-semiconductors',
    short: 'IEEE Spectrum (the node is nonsense)',
  },
  {
    key: 'itrs-1999',
    num: 86,
    title: 'International Technology Roadmap for Semiconductors — 1999 edition',
    publisher: 'Semiconductor Industry Association (ITRS)',
    url: 'http://cva.stanford.edu/classes/cs99s/papers/roadmap1999.pdf',
    short: 'ITRS 1999',
  },
  {
    key: 'itrs-2001',
    num: 87,
    title: 'International Technology Roadmap for Semiconductors — 2001 Executive Summary',
    publisher: 'Semiconductor Industry Association (ITRS)',
    url: 'https://www.semiconductors.org/wp-content/uploads/2018/08/2001-Executive-Summary.pdf',
    short: 'ITRS 2001',
  },
  {
    key: 'semiconductor-scale',
    num: 88,
    title: 'List of semiconductor scale examples',
    publisher: 'Wikipedia (CC BY-SA 4.0)',
    url: 'https://en.wikipedia.org/wiki/List_of_semiconductor_scale_examples',
    short: 'Wikipedia (semiconductor scale)',
  },
  {
    key: 'chm-sigate',
    num: 89,
    title: '1968: Silicon Gate Technology Developed for ICs',
    publisher: 'Computer History Museum — The Silicon Engine',
    url: 'https://www.computerhistory.org/siliconengine/silicon-gate-technology-developed-for-ics/',
    short: 'Computer History Museum (silicon gate)',
  },
  {
    key: 'faggin-sgt',
    num: 90,
    title: 'The MOS Silicon Gate Technology and the First Microprocessors',
    publisher: 'Federico Faggin — first-person account, hosted at intel4004.com',
    url: 'http://www.intel4004.com/The_MOS_Silicon_Gate_Technology_and_the_First_Microprocessors.pdf',
    short: 'Faggin (silicon gate)',
  },
  {
    key: 'asml-light',
    num: 91,
    title: 'Light and lasers — lithography principles',
    publisher: 'ASML',
    url: 'https://www.asml.com/en/technology/lithography-principles/light-and-lasers',
    short: 'ASML (luz e lasers)',
  },
  {
    key: 'asml-euv-products',
    num: 92,
    title: 'EUV lithography systems — products',
    publisher: 'ASML',
    url: 'https://www.asml.com/en/products/euv-lithography-systems',
    short: 'ASML (sistemas EUV)',
  },
  {
    key: 'asml-nxe3800e',
    num: 93,
    title: 'TWINSCAN NXE:3800E — EUV lithography systems',
    publisher: 'ASML',
    url: 'https://www.asml.com/en/products/euv-lithography-systems/twinscan-nxe-3800e',
    short: 'ASML NXE:3800E',
  },
  {
    key: 'asml-nxe3600d',
    num: 94,
    title: 'TWINSCAN NXE:3600D — EUV lithography systems',
    publisher: 'ASML',
    url: 'https://www.asml.com/en/products/euv-lithography-systems/twinscan-nxe-3600d',
    short: 'ASML NXE:3600D',
  },
  {
    key: 'asml-highna',
    num: 95,
    title: '5 things you should know about High NA EUV lithography',
    publisher: 'ASML',
    url: 'https://www.asml.com/en/company/stories/2024/5-things-high-na-euv',
    short: 'ASML (High NA EUV)',
  },
  {
    key: 'asml-exe5200b',
    num: 96,
    title: 'TWINSCAN EXE:5200B — EUV lithography systems',
    publisher: 'ASML',
    url: 'https://www.asml.com/en/products/euv-lithography-systems/twinscan-exe-5200b',
    short: 'ASML EXE:5200B',
  },
  {
    key: 'asml-duv',
    num: 97,
    title: 'DUV lithography systems — products',
    publisher: 'ASML',
    url: 'https://www.asml.com/en/products/duv-lithography-systems',
    short: 'ASML (sistemas DUV)',
  },
  {
    key: 'asml-investor-euv',
    num: 98,
    title: 'EUV products and business opportunity',
    publisher: 'ASML Investor Day 2024 — Peter van Oppen',
    url: 'https://media.asml.com/asmlnetherlaaea-asmlcom-prd-5369/media/project/asmlcom/asmlcom/asml/files/investors/investor-days/2024/04_euv-products-and-business-opportunity---peter-vanoppen.pdf',
    short: 'ASML (roadmap EUV)',
  },
  {
    key: 'trumpf-euv',
    num: 99,
    title: 'EUV drive laser',
    publisher: 'TRUMPF',
    url: 'https://www.trumpf.com/en_INT/solutions/applications/euv-lithography/euv-drive-laser/',
    short: 'TRUMPF (laser EUV)',
  },
  {
    key: 'intel-exe5200b',
    num: 100,
    title: 'How collaboration in High NA EUV and transistor R&D are shaping future waves of device innovation',
    publisher: 'Intel (blog, dezembro de 2025)',
    url: 'https://community.intel.com/t5/Blogs/Intel-Foundry/Systems-Foundry-for-the-AI-Era/How-Collaboration-in-High-NA-EUV-and-Transistor-R-D-Are-Shaping/post/1730050',
    short: 'Intel (EXE:5200B)',
  },
  {
    key: 'branch-euv',
    num: 101,
    title: 'The $200M machine that prints microchips: the EUV photolithography system',
    publisher: 'Branch Education (vídeo, patrocinado pela ASML)',
    url: 'https://www.youtube.com/watch?v=B2482h_TNwg',
    short: 'Branch Education (EUV)',
  },
  {
    key: 'asml-highna-video',
    num: 102,
    title: 'Inside the machine: how a High NA system generates EUV light',
    publisher: 'ASML (vídeo)',
    url: 'https://www.youtube.com/watch?v=MfFGRl00LKY',
    short: 'ASML (vídeo High NA)',
  },
  {
    key: 'asml-euv-podcast',
    num: 103,
    title: 'Making EUV work: Episode 3 — from lab to fab (Four Decades of ASML)',
    publisher: 'ASML (vídeo/podcast)',
    url: 'https://www.youtube.com/watch?v=EWVJ1Iwa00E',
    short: 'ASML (podcast EUV)',
  },
  {
    key: 'laserfocus-euv',
    num: 104,
    title: 'How does the laser technology in EUV lithography work?',
    publisher: 'Andreas Thoss — Laser Focus World',
    url: 'https://www.laserfocusworld.com/blogs/article/14039015/how-does-the-laser-technology-in-euv-lithography-work',
    short: 'Laser Focus World (laser EUV)',
  },
  {
    key: 'bits-chips-exe5200b',
    num: 105,
    title: 'ASML ships first high-NA EUV production scanner',
    publisher: 'Paul van Gerven — Bits&Chips (julho de 2025)',
    url: 'https://bits-chips.com/article/asml-ships-first-high-na-euv-production-scanner/',
    short: 'Bits&Chips (EXE:5200B)',
  },
  {
    key: 'asml-unveiling-highna',
    num: 106,
    title: 'Unveiling High NA EUV',
    publisher: 'ASML (video)',
    url: 'https://www.youtube.com/watch?v=h_zgURwr6nA',
    short: 'ASML (High NA, video)',
  },
]

export const citationsByKey = Object.fromEntries(list.map((c) => [c.key, c])) as Record<
  string,
  Citation
>

export const citationsByNum = Object.fromEntries(list.map((c) => [c.num, c])) as Record<
  number,
  Citation
>

export function getCitation(key: string): Citation | undefined {
  return citationsByKey[key]
}

export const USGS_MCS_YEARS = [2020, 2021, 2022, 2023, 2024, 2025] as const

export function usgsMcsUrl(year: number): string {
  return `https://pubs.usgs.gov/periodicals/mcs${year}/mcs${year}-silicon.pdf`
}

export const allCitations = [...list].sort((a, b) => a.num - b.num)
